/**
 * Whitelist module.
 *
 * The whitelist is UI-only — relay and Blossom access remain public.
 * The record button is hidden for pubkeys not on the list.
 *
 * Sources (merged as union):
 *   1. Per-issue JSON at /data/whitelist-<issueId>.json
 *      (generated by dm-outreach.ts from the Compass pipeline)
 *   2. Standing roster at /data/npubs.yml
 *      (all known contributors, persists across issues)
 *
 * Any npub on either list can record under any section.
 * Section map is a UI suggestion, not a gate.
 */

import { nip19 } from 'nostr-tools'

const WHITELIST_CACHE = new Map<string, Set<string>>()

/**
 * Fetch and merge per-issue whitelist + standing roster.
 * Returns a Set of hex pubkeys.
 * Gracefully degrades: if one source fails, uses the other.
 */
export async function fetchWhitelist(issueId: string): Promise<Set<string>> {
  const cached = WHITELIST_CACHE.get(issueId)
  if (cached) return cached

  const [issueList, standingList] = await Promise.allSettled([
    fetchIssueWhitelist(issueId),
    fetchStandingRoster(),
  ])

  const combined = new Set<string>()

  if (issueList.status === 'fulfilled') {
    for (const p of issueList.value) combined.add(p)
  }
  if (standingList.status === 'fulfilled') {
    for (const p of standingList.value) combined.add(p)
  }

  WHITELIST_CACHE.set(issueId, combined)
  return combined
}

/** Fetch /data/whitelist-<issueId>.json — array of hex pubkeys or npubs. */
async function fetchIssueWhitelist(issueId: string): Promise<string[]> {
  const res = await fetch(`/data/whitelist-${issueId}.json`)
  if (!res.ok) return []
  const data = await res.json() as unknown
  if (!Array.isArray(data)) return []
  return (data as string[]).map(normalizeToHex).filter((p): p is string => p !== null)
}

/**
 * Fetch /data/npubs.yml — simple YAML: name: npub1xxx or name: hex
 * We parse this client-side with a minimal regex rather than a YAML library.
 */
async function fetchStandingRoster(): Promise<string[]> {
  const res = await fetch('/data/npubs.yml')
  if (!res.ok) return []
  const text = await res.text()
  return parseNpubsYml(text)
}

/** Parse npubs.yml — supports both formats:
 *  Flat:   "name: npub1..." or "name: <hex>"
 *  Nested: "- pubkey: <hex>" / "pubkey: <hex>" / "- npub: npub1..." list entries
 */
function parseNpubsYml(yaml: string): string[] {
  const pubkeys: string[] = []
  for (const line of yaml.split('\n')) {
    const trimmed = line.trim().replace(/^-\s*/, '')
    if (!trimmed || trimmed.startsWith('#')) continue
    const colonIdx = trimmed.indexOf(':')
    if (colonIdx === -1) continue
    const value = trimmed.slice(colonIdx + 1).trim().replace(/^["']|["']$/g, '')
    const hex = normalizeToHex(value)
    if (hex) pubkeys.push(hex)
  }
  return pubkeys
}

/** Convert npub1... to hex, or pass through if already hex. */
function normalizeToHex(pubkey: string): string | null {
  if (!pubkey) return null
  if (pubkey.startsWith('npub1')) {
    try {
      const decoded = nip19.decode(pubkey)
      if (decoded.type === 'npub') return decoded.data as string
    } catch {
      return null
    }
  }
  if (/^[0-9a-f]{64}$/i.test(pubkey)) return pubkey.toLowerCase()
  return null
}

/** Check if a pubkey is whitelisted for a given issue. */
export function isWhitelisted(pubkey: string, whitelist: Set<string>): boolean {
  return whitelist.has(pubkey.toLowerCase())
}

/** Invalidate the cache for a specific issue (call after whitelist update). */
export function invalidateWhitelistCache(issueId: string): void {
  WHITELIST_CACHE.delete(issueId)
}
